### PR TITLE
Correct export of trajectory

### PR DESCRIPTION
**Pull request by MalcolmMielle**
Instead of exporting the DMP, the DMPTrajectory is saved at the end of the reproduction generation. The save strategy for DMP Trajectory is uniform with the demonstration software so that field test and maintenance test have the same data format

### CODE REVIEW

**Review by PanchettiLorenzo — APPROVED** [review]
Fine with me! Would we revert back save_dmp then?

**Comment by MalcolmMielle** [comment]
I like the new save DMP :). I think we should convert the old npy to json and correct the load dmp :). But later

**Comment by MalcolmMielle** [comment]
I actually will push a small fix

**Review by PanchettiLorenzo — APPROVED** [review]

**Comment by MalcolmMielle** [comment]
More fixes incomming sorry X)

**Comment by MalcolmMielle** [comment]
I'll ping you when it seems all good

**Comment by MalcolmMielle** [comment]
Should be good!

**Review by PanchettiLorenzo — APPROVED** [review]
Everything is working as expected! Well done :)

**Pull request merged**
