### PR TITLE
Added maintenance dataset and scores

### PR DESCRIPTION
**Pull request by PanchettiLorenzo**

### CODE REVIEW

**Comment by MalcolmMielle** [comment]
OK I feel like something is weird either in how we apply noise or on the type of noise we are having: noise 25deg leads to GMCC that are perfect, that i not normal :(

```
{
    "gmccs": {
        "mean": 0.9999825768196966,
        "std": 0.00010837224573459692
    },
    "joints mean absolute error": {
        "mean": 0.13657308940957916,
        "std": 0.10917966774892429
    }
}
```

Maybe adding the noise as a Gaussian noise _centered on zero_ is the problem. Maybe most of the tests we are running do not add enough noise? This is an unbelievable result to me :/. Could you try to visualize the trajectory with the 25% noise added and see if they are really noisy? Would that be possible?

**Comment by PanchettiLorenzo** [comment]
Yes I can visualize the noisy trajectory compared to the regression :) I am surprised as well that it is so good
I checked in their paper and they have pretty incredible results too for noisy trajectories

**Comment by PanchettiLorenzo** [comment]
image

**Comment by PanchettiLorenzo** [comment]
I totally agree! at first interpretation without visualisation we were puzzled too 
I will create the graph and send on team-paper

**Review by MalcolmMielle — APPROVED** [review]

**Pull request merged**
