### PR TITLE
Trajectories

### PR DESCRIPTION
**Pull request by MalcolmMielle**
This commit refactors the trajectories and simplifies DMP by using a timed trajectory. Furthermore, the export import of trajectory is uniform now

### CODE REVIEW

**Comment by PanchettiLorenzo** [comment]
Have you tested it? A bit scared of the huge refactoring

**Comment by MalcolmMielle** [comment]
It passes all the unit tests (and not on the first try) ;). That include trajectory and dmp unit tests. It doesn't change anything to how it works :)

**Comment by MalcolmMielle** [comment]
I'm not saying it's big proof 100 but to the best of my ability I think it is :)

**Review by PanchettiLorenzo — APPROVED** [review]
All good, just found a small issue with an utility function :)

**Pull request merged**
